### ISSUE TITLE
App crashes after clicking on the social links of Developers

### ISSUE THREAD

**Issue by drigio** [PatilShreyas/GDGPune-DevFest19-Android#21]
Following is the logcat :

> **2019-08-10 19:48:22.115 13478-13478/com.gdg.pune.devfest19 E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.gdg.pune.devfest19, PID: 13478
    android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
        at android.app.ContextImpl.startActivity(ContextImpl.java:912)
        at android.app.ContextImpl.startActivity(ContextImpl.java:888)
        at android.content.ContextWrapper.startActivity(ContextWrapper.java:379)
        at com.gdg.pune.devfest19.viewholder.DeveloperViewHolder$bind$onLinkClickListener$1.onClick(DeveloperViewHolder.kt:50)
        at android.view.View.performClick(View.java:6597)
        at android.view.View.performClickInternal(View.java:6574)
        at android.view.View.access$3100(View.java:778)
        at android.view.View$PerformClick.run(View.java:25885)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6719)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)**

Tested on Android 9.0 Pie. Works on 7.0 Nougat and 8.1 Oreo

A simple setting of flag might solve the issue.

**Comment by PatilShreyas** [comment]
@drigio Thanks for filing this issue. We'll try to fix it.

**Comment by PatilShreyas** [comment]
Fixed and implemented. Thanks @drigio.
